### PR TITLE
Fix: CI test script failing due to missing `kill` PID after Jest execution

### PR DESCRIPTION
**Pull request by 0xjei**

### CODE REVIEW

**Comment by gurrpi** [comment]
Screenshot 2023-03-27 at 21 49 49

When does this failure happen? The recent CI history shows it has been passed until the latest run.

**Comment by gurrpi** [comment]
https://github.com/facebook/jest/issues/9324#issuecomment-1249682315 might be useful info

**Comment by 0xjei** [comment]
> Screenshot 2023-03-27 at 21 49 49
> 
> When does this failure happen? The recent CI history shows it has been passed until the latest run.

Mostly happened after switching to yarn 3 which doesn't like the `kill` argument at the end of the npm script (changed with `pkill` but didn't work).

**Comment by baumstern** [comment]
Closing this since the problem that this PR trying to solve has been fixed by https://github.com/quadratic-funding/mpc-phase2-suite/pull/371

**Pull request closed without merging**
