### PR TITLE
Add CI Github Action for running tests

### PR DESCRIPTION
**Pull request by 0xjei**

### CODE REVIEW

**Comment by gurrpi** [comment]
> Hey @gurrpi, sorry for calling you on it here. I'm dealing with the `serviceAccountKey.json` file needed to use the Admin SDK in testing. How could we pass it on to Github Action? Maybe using secrets? Feel free to modify this PR, I have only defined an initial base layer to work on for the test CI.
> 
> * Reference: https://firebase.google.com/docs/admin/setup

It would works to pass required auth key by using encrypted environment variable (aka. GitHub secret). How about to have e2e which could run locally (by using [Firebase Emulator suite](https://firebase.google.com/docs/emulator-suite) as we mentioned before)? It will run much faster so dev can get feedback much earlier and don't have to deal with a hassle of configuration for remote environments. Remote e2e test would ensures our code will run correctly on real world infrastructure.

**Comment by 0xjei** [comment]
> > Hey @gurrpi, sorry for calling you on it here. I'm dealing with the `serviceAccountKey.json` file needed to use the Admin SDK in testing. How could we pass it on to Github Action? Maybe using secrets? Feel free to modify this PR, I have only defined an initial base layer to work on for the test CI.
> > 
> > * Reference: https://firebase.google.com/docs/admin/setup
> 
> It would works to pass required auth key by using encrypted environment variable (aka. GitHub secret). Btw, how about to have e2e which could run locally (by using [Firebase Emulator suite](https://firebase.google.com/docs/emulator-suite) as we mentioned before)? It will run much faster so dev can get feedback much earlier and don't have to deal with a hassle of configuration for remote environments. Remote e2e test would ensures our code will run correctly on real world infrastructure.

Great for Github Secrets :star:  

Interesting as a proposal what concerns the usage of Firebase Local Emulator. When I had proposed to @daodesigner told me that it would be good for unit testing and not for e2e testing. However, we could have two e2e tests and decide whether to run them locally (emulator) or remotely (deployed dev environment). Is that what you meant? :)

**Comment by daodesigner** [comment]
Is it possible to do locally on PRs between branches and remote for merging to main? (Feel free to push back on this)

**Comment by 0xjei** [comment]
> More urgent/important is definitely having tests that work against prod. Is it possible to do 'locally' on PRs between branches and remote for merging to main? Feel free to push back on this if it's more than a simple switch you flip.

It would seem easy enough switching between emulator and deployed infrastructure. What really changes is the initialization of Firebase services (whether emulated or not). I think this can be solved with an environment variable set when launching the tests.

__Examples__
- Here is an example in using emulator => https://github.com/firebase/emulators-codelab/blob/master/codelab-final-state/functions/test.js#L67 (note the emulator init above L46).
- An example without emulator but with the infra deployed can be found in our package actions => https://github.com/quadratic-funding/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/index.test.ts#L94

LMK your thoughts @daodesigner @gurrpi

**Comment by gurrpi** [comment]
> However, we could have two e2e tests and decide whether to run them locally (emulator) or remotely (deployed dev environment). Is that what you meant? :)

RIght! Thanks for the clarification.

---

Definitely agree with @daodesigner, let's push back local e2e and move the current scripts of the `yarn test` command to something more specific name (e.g. `test-ci`, so `yarn test-ci` command would call it).
Think following [package.json file](https://github.com/parcel-bundler/parcel/blob/v2/package.json#L27-L29) would be a good reference of separating test commands:
```
    "test:unit": "cross-env NODE_ENV=test mocha && cargo test --package parcel-js-swc-core --lib",
    "test:integration": "yarn workspace @parcel/integration-tests test",
    "test:integration-ci": "yarn workspace @parcel/integration-tests test-ci",
    "test": "yarn test:unit && yarn test:integration",
```

My points was _`yarn test` command should pass without any background knowledge_. 

1. Scanning environment variables to detect the target environment can be an alternative to renaming the command. IMO renaming yarn command would be easier task. Feel free to pick any of these approaches (or 3rd way) if it makes sense.
2. having local e2e test to fulfil this idea. But it might require a degree of efforts, easy efforts are still an efforts XD,  to introduce Firebase Emulator.

**Comment by ctrlc03** [comment]
Steps for testing with `serviceAccountKey.json` on prod:

Create secret called `SERVICE_ACCOUNT` with the entire JSON object

Use following actions:

```
jobs:
    test:
        name: Test
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: yarn install

            - name: Create JSON
              id: create-json
              uses: jsdaniell/create-json@v1.2.1
              with:
                name: "serviceAccountKey.json"
                json: ${{ secrets.SERVICE_ACCOUNT }}
                dir: './packages/backend/'

            - name: Test
              run: yarn test:option
```

**Comment by ctrlc03** [comment]
> 

Complete [solution](https://github.com/ctrlc03/mpc-phase2-suite/actions/runs/3602402334/jobs/6069315756) to run both backend and actions tests in one workflow (Requires to set all .env variables as GitHub secrets):

Workflow [file](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/.github/workflows/test.yaml)
Package-json new script: `"test:ci": "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit --coverage=false",`

Changes to [`./packages/actions/test/utils/index.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/utils/index.ts) - will need to remove .env.test and just call it .env for local testing
Changes to [`./packages/actions/test/index.test.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/index.test.ts) - add greater JEST timeout

**Comment by gurrpi** [comment]
> > Complete [solution](https://github.com/ctrlc03/mpc-phase2-suite/actions/runs/3602402334/jobs/6069315756) to run both backend and actions tests in one workflow (Requires to set all .env variables as GitHub secrets):
> > Workflow [file](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/.github/workflows/test.yaml) Package-json new script: `"test:ci": "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit --coverage=false"`
> > Changes to [`./packages/actions/test/utils/index.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/utils/index.ts) - will need to remove .env.test and just call it .env for local testing Changes to [`./packages/actions/test/index.test.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/index.test.ts) - increase JEST timeout
> 
> My takeaways after proposals and discussions:
> 
> * We continue with testing exclusively in the remote development environment. The local environment (i.e., Firebase local emulator) will be introduced along with unit testing. At that point, we would be complicating the workflow, now we just need to focus on e2e test for going in production (thanks @daodesigner for heads up).
> * We would have differentiation between test commands to achieve this goal `yarn test command should pass without any background knowledge` stated by @gurrpi. This way, we could call exclusively `yarn test:ci` for remote workflow, while `yarn test` will work in the future with unit and e2e tests locally in the emulator (no effort for configs). So, just run `yarn test:e2e-local` for testing locally on your machine right now (will be deprecated later and you will need the `serviceAccountKey.json`).
> * Thanks @ctrlc03 for the input, by transforming the serviceAccountKey.json as secret and small arrangements, we could actually achieve the goal of this PR.
> 
> Thank you all and collaborating with you is always exciting. I'm learning a lot of things every day <3 Keep up the good work!

Great summary!
You mean `yarn test:e2e-local` would run a test against prod environment (which does same as `yarn test:ci`) but for human, not CI?

**Comment by 0xjei** [comment]
> > > Complete [solution](https://github.com/ctrlc03/mpc-phase2-suite/actions/runs/3602402334/jobs/6069315756) to run both backend and actions tests in one workflow (Requires to set all .env variables as GitHub secrets):
> > > Workflow [file](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/.github/workflows/test.yaml) Package-json new script: `"test:ci": "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit --coverage=false"`
> > > Changes to [`./packages/actions/test/utils/index.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/utils/index.ts) - will need to remove .env.test and just call it .env for local testing Changes to [`./packages/actions/test/index.test.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/index.test.ts) - increase JEST timeout
> > 
> > 
> > My takeaways after proposals and discussions:
> > 
> > * We continue with testing exclusively in the remote development environment. The local environment (i.e., Firebase local emulator) will be introduced along with unit testing. At that point, we would be complicating the workflow, now we just need to focus on e2e test for going in production (thanks @daodesigner for heads up).
> > * We would have differentiation between test commands to achieve this goal `yarn test command should pass without any background knowledge` stated by @gurrpi. This way, we could call exclusively `yarn test:ci` for remote workflow, while `yarn test` will work in the future with unit and e2e tests locally in the emulator (no effort for configs). So, just run `yarn test:e2e-local` for testing locally on your machine right now (will be deprecated later and you will need the `serviceAccountKey.json`).
> > * Thanks @ctrlc03 for the input, by transforming the serviceAccountKey.json as secret and small arrangements, we could actually achieve the goal of this PR.
> > 
> > Thank you all and collaborating with you is always exciting. I'm learning a lot of things every day <3 Keep up the good work!
> 
> Great summary! You mean `yarn test:e2e-local` would run a test against prod environment (which does same as `yarn test:ci`) but for human, not CI?

Yes, exactly @gurrpi! This command will be just a temporary command for running e2e "manually" (probably will be something like: `test:e2e-local: "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit"` while `test:ci: "jest --forceExit --coverage=false"`)

**Comment by gurrpi** [comment]
> > > > Complete [solution](https://github.com/ctrlc03/mpc-phase2-suite/actions/runs/3602402334/jobs/6069315756) to run both backend and actions tests in one workflow (Requires to set all .env variables as GitHub secrets):
> 
> > > > Workflow [file](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/.github/workflows/test.yaml) Package-json new script: `"test:ci": "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit --coverage=false"`
> 
> > > > Changes to [`./packages/actions/test/utils/index.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/utils/index.ts) - will need to remove .env.test and just call it .env for local testing Changes to [`./packages/actions/test/index.test.ts`](https://github.com/ctrlc03/mpc-phase2-suite/blob/refactor/monorepo/packages/actions/test/index.test.ts) - increase JEST timeout
> 
> > > 
> 
> > > 
> 
> > > My takeaways after proposals and discussions:
> 
> > > 
> 
> > > * We continue with testing exclusively in the remote development environment. The local environment (i.e., Firebase local emulator) will be introduced along with unit testing. At that point, we would be complicating the workflow, now we just need to focus on e2e test for going in production (thanks @daodesigner for heads up).
> 
> > > * We would have differentiation between test commands to achieve this goal `yarn test command should pass without any background knowledge` stated by @gurrpi. This way, we could call exclusively `yarn test:ci` for remote workflow, while `yarn test` will work in the future with unit and e2e tests locally in the emulator (no effort for configs). So, just run `yarn test:e2e-local` for testing locally on your machine right now (will be deprecated later and you will need the `serviceAccountKey.json`).
> 
> > > * Thanks @ctrlc03 for the input, by transforming the serviceAccountKey.json as secret and small arrangements, we could actually achieve the goal of this PR.
> 
> > > 
> 
> > > Thank you all and collaborating with you is always exciting. I'm learning a lot of things every day <3 Keep up the good work!
> 
> > 
> 
> > Great summary! You mean `yarn test:e2e-local` would run a test against prod environment (which does same as `yarn test:ci`) but for human, not CI?
> 
> 
> 
> Yes, exactly @gurrpi! This command will be just a temporary command for running e2e "manually" (probably will be something like: `test:e2e-local: "export GOOGLE_APPLICATION_CREDENTIALS=\"./packages/backend/serviceAccountKey.json\" && jest --forceExit"` while `test:ci: "jest --forceExit --coverage=false"`)

All looks good! Will ping you about remote environment configuration soon.

**Comment by 0xjei** [comment]
Outdated due to unexpected issues with the forked repo. Here only for reference. New PR #229

**Pull request closed without merging**
